# Generated by Django 2.2.3 on 2019-07-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fingerprintData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='fingerprintData/static/vendor/img/no-img.jpg', upload_to='fingerprintData/static/vendor/img/'),
        ),
    ]
